---
name: Authen-Prepare
version: 0.04
author:
  - 'David Narayan  C<< <dnarayan@cpan.org> >>'
abstract: Prepare a set of authentication credentials
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Fcntl: 0
  File::Spec: 0.80
  IO::Prompt: 0
  Readonly: 0
  Text::Glob: 0
build_requires:
  Test::Exception: 0
  Test::Expect: 0
  Test::More: 0.42
  Test::Warn: 0
provides:
  Authen::Prepare:
    file: lib/Authen/Prepare.pm
    version: 0.04
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
